name: ahda_app
description: A new Flutter project for managing custody and expenses.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cloud_functions: ^4.5.3
  firebase_messaging: ^14.7.9
  image_picker: ^1.0.7
  local_auth: ^2.1.8
  excel: ^4.0.2
  path_provider: ^2.1.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
